name: consistency

on:
  push:
  workflow_dispatch:

jobs:
  consistency:
    uses: OpenAutomatedDriving/dev-environment/.github/workflows/repository_consistency.yml@submodule # TODO: revert to main
    secrets: inherit
