name: consistency

on:
  push:
  workflow_dispatch:

jobs:
  consistency:
    uses: openads-project/openads-dev-environment/.github/workflows/consistency.yml@consistency-forks
    with:
      skip-checks: dev_environment_at_remote_main
    secrets: inherit
